---

- include_vars: main.yml

- name: 'Create the web user'
  user: name=web shell=/bin/bash

- name: 'Create/activate virtualenv and install dependencies'
  pip: requirements='{{ web_dir }}/requirements.txt' virtualenv='{{ web_venv }}'

- name: 'Create logging directory'
  file: path='{{ web_log_dir }}' owner=web group=web state=directory

- name: 'Create src directory'
  file: path='{{ src_dir }}' owner=web group=web state=directory

- name: 'Copy the python runner'
  template: src=python_runner.sh.j2 dest='{{ python_runner }}' mode=0744 owner=web

- name: 'Copy the supervisor config'
  template: src=supervisor_web.conf.j2 dest='{{ supervisor_config }}'

- name: 'Start web application server'
  shell: supervisorctl reload
