---
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
  - chucknorris
  - embeddable-build-status
  - git
  - github
  - greenballs
  - junit
  - shiningpanda
  - sonar
  - ssh
jenkins_url_prefix: ""
